INSERT INTO panel_check (code_error,
                         name_error,
                         description_error,
                         priority,
                         group_name,
                         group_description)
VALUES
(1100, 'Missing title', 'Title are an important part of SEO optimization of your website and are highly valued by search engines',
1, 'Title', 'The Title meta tag helps to shape the title of the web page that appears in the search results'),
(1101, 'Multiple meta titles found on page', 'On page must be only one title tag',
1, 'Title', 'The Title meta tag helps to shape the title of the web page that appears in the search results'),
(1110, 'Too short title', 'Title must be at least 80 characters',
1, 'Title', 'The Title meta tag helps to shape the title of the web page that appears in the search results'),
(1111, 'Too long title', 'Title must be no more than 140 characters',
1, 'Title', 'The Title meta tag helps to shape the title of the web page that appears in the search results'),
(1120, 'Missing description', 'The description is needed to describe your page to the search robot and the users',
1, 'Description', 'Using the Description meta tag, you can create a description of the web page that will be available to both a user and the search engine robot'),
(1121, 'Multiple meta descriptions found on page', 'On page must be only one description tag',
1, 'Description', 'Using the Description meta tag, you can create a description of the web page that will be available to both a user and the search engine robot'),
(1130, 'Too short description', 'Description must be at least 50 characters',
1, 'Description', 'Using the Description meta tag, you can create a description of the web page that will be available to both a user and the search engine robot'),
(1131, 'Too long description', 'Description must be no more than 160 characters',
1, 'Description', 'Using the Description meta tag, you can create a description of the web page that will be available to both a user and the search engine robot'),
(1140, 'Missing keywords', 'Key phrases in the keywords tag must be filled with a comma, separated by a space.',
1, 'Keywords', 'The keywords meta tag is a fragment of code used to indicate a list of keywords relevant to a particular page. Search engines stopped considering manually written key queries in the website code. However, their use makes sense just because everything can change.'),
(1141, 'Multiple meta keywords found on page', 'On page must be only one keywords tag',
1, 'Keywords', 'The keywords meta tag is a fragment of code used to indicate a list of keywords relevant to a particular page. Search engines stopped considering manually written key queries in the website code. However, their use makes sense just because everything can change.'),
(1150, 'Not enough keywords', 'It must be at least 3 key phrases in the keywords',
1, 'Keywords', 'The keywords meta tag is a fragment of code used to indicate a list of keywords relevant to a particular page. Search engines stopped considering manually written key queries in the website code. However, their use makes sense just because everything can change.'),
(1151, 'Too much keywords', 'It must be no more 10 key phrases in the keywords',
1, 'Keywords', 'The keywords meta tag is a fragment of code used to indicate a list of keywords relevant to a particular page. Search engines stopped considering manually written key queries in the website code. However, their use makes sense just because everything can change.'),
(1160, 'Missing h1', 'h1 heading is an influential ranking factor and should be present on every page of your website',
1, 'Headings', 'The tags <h1> — <h6> play an important role in SEO optimization: search robots first of all scan headlines and form an issue based on key information from articles'),
(1161, 'Multiple h1 found on page', 'If you use the tag more than once, its significance will fall. As a result, the search engines will lower the ranking of a page or the entire site',
1, 'Headings', 'The tags <h1> — <h6> play an important role in SEO optimization: search robots first of all scan headlines and form an issue based on key information from articles'),
(1170, 'Missing h2', 'For better ranking in the search results, you need to add the tag h2',
1, 'Headings', 'The tags <h1> — <h6> play an important role in SEO optimization: search robots first of all scan headlines and form an issue based on key information from articles'),
(1180, 'Missing h3', 'For better ranking in the search results, you need to add the tag h3',
1, 'Headings', 'The tags <h1> — <h6> play an important role in SEO optimization: search robots first of all scan headlines and form an issue based on key information from articles');

